#!/bin/bash
# Test the bib-convu script.

source $(dirname $0)/character_arrays.sh

# Functions to check single character substitutions.
check_latex() {
    # Check for multiple replacements on one line, drop backslash escaping.
    latex=$(sed 's/\\\\/\\/g' <<< "$1 $1$1")
    unicode=$(sed 's/\\\\/\\/g' <<< "$2 $2$2")
    assertEquals "convert »$1« to »$2«" "$unicode" "$(bib-convu $* <<< "$latex")"
}

check_unicode() {
    # Check for multiple replacements on one line, drop backslash escaping.
    latex=$(sed 's/\\\\/\\/g' <<< "$1 $1$1")
    unicode=$(sed 's/\\\\/\\/g' <<< "$2 $2$2")
    assertEquals "keep »$2« as »$2«"    "$unicode" "$(bib-convu $* <<< "$unicode")"
}

# _____________________________________________________________________________

testLatexToUnicodeConversion() {
  i=0; while [ $i -lt $MIN_COUNT ]; do i=$(($i + 1));
    # Minimum list of replacements must be fulfilled with option -s.
    check_latex "${MIN_LATEX_ARRAY[$i]}" "${MIN_UNICODE_ARRAY[$i]}" -s
  done
  i=0; while [ $i -lt $ALL_COUNT ]; do i=$(($i + 1));
    check_latex "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}"
  done
}

testUnicodeToUnicodeUnchanged() {
  i=0; while [ $i -lt $ALL_COUNT ]; do i=$(($i + 1));
    check_unicode "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}" -s
    check_unicode "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}"
  done
}

# Load and run shUnit2.
. shunit2/shunit2
