#!/bin/bash
# Test the bib-convl script.

source $(dirname $0)/character_arrays.sh

# Functions to check single character substitutions.
check_unicode() {
    # Check for multiple replacements on one line, drop backslash escaping.
    latex=$(sed 's/\\\\/\\/g' <<< "$1 $1$1")
    unicode=$(sed 's/\\\\/\\/g' <<< "$2 $2$2")
    assertEquals "convert »$2« to »$1«" "$latex" "$(bib-convl $* <<< "$unicode")"
}

check_latex() {
    # Check for multiple replacements on one line, drop backslash escaping.
    latex=$(sed 's/\\\\/\\/g' <<< "$1 $1$1")
    unicode=$(sed 's/\\\\/\\/g' <<< "$2 $2$2")
    assertEquals "keep »$1« as »$1«"    "$latex" "$(bib-convl $* <<< "$latex")"
}

# _____________________________________________________________________________

testUnicodeToLatexConversion() {
  i=0; while [ $i -lt $MIN_COUNT ]; do i=$(($i + 1));
    # Minimum list of replacements must be fulfilled with option -s.
    check_unicode "${MIN_LATEX_ARRAY[$i]}" "${MIN_UNICODE_ARRAY[$i]}" -s
  done
  i=0; while [ $i -lt $ALL_COUNT ]; do i=$(($i + 1));
    check_unicode "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}"
  done
}

testLatexToLatexUnchanged() {
  i=0; while [ $i -lt $ALL_COUNT ]; do i=$(($i + 1));
    check_latex "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}" -s
    check_latex "${ALL_LATEX_ARRAY[$i]}" "${ALL_UNICODE_ARRAY[$i]}"
  done
}

testAccentsToLatex() {
    check_unicode "\\'{a}" "á"
    check_unicode "\\'{e}" "é"
    check_unicode "\\'{i}" "í"
    check_unicode "\\'{o}" "ó"
    check_unicode "\\'{u}" "ú"
    check_unicode "\\'{A}" "Á"
    check_unicode "\\'{E}" "É"
    check_unicode "\\'{I}" "Í"
    check_unicode "\\'{O}" "Ó"
    check_unicode "\\'{U}" "Ú"
    check_unicode "\\'{c}" "\\'{c}" -s
    check_unicode "\\'{n}" "\\'{n}" -s
    check_unicode "\\'{y}" "\\'{y}" -s
    check_unicode "\\'{c}" "ć"
    check_unicode "\\'{n}" "ń"
    check_unicode "\\'{y}" "ý"
    # Additional tests for formatting.
    check_unicode "\\\`{a}" "\\\`a"
    check_unicode "\\\`{e}" "\\\`e"
    check_unicode "\\'{a}" "\\'a"
    check_unicode "\\'{e}" "\\'e"
    check_unicode "\\'{i}" "\\'i"
    check_unicode "\\'{o}" "\\'o"
    check_unicode "\\'{u}" "\\'u"
    check_unicode "\\'{A}" "\\'A"
    check_unicode "\\'{E}" "\\'E"
    check_unicode "\\'{I}" "\\'I"
    check_unicode "\\'{O}" "\\'O"
    check_unicode "\\'{U}" "\\'U"
    check_unicode "\\'{c}" "\\'c"
    check_unicode "\\'{n}" "\\'n"
    check_unicode "\\'{y}" "\\'y"
    # Avoid formatting mistakes.
    check_unicode "Escart{\'\i}n" "Escart{\'\i}n" # must not put \'{\}
}

# Load and run shUnit2.
. shunit2/shunit2
